### ISSUE TITLE
The clear input does nothing

### ISSUE THREAD

**Issue by tokict** [khaiql/react-native-progressive-input#6]
I cant click on clear input as every time I want to click it, the keyboard goes away first and the x dissapears with it

**Comment by khaiql** [comment]
Please provide more context, screenshot and your code

**Comment by Balasnest** [comment]
@khaiql  Me too facing this issue. 

**Expected behaviour:**
When pressing the clear icon button, the input text value should clear and it should call the function to the clear state value also.

**Actual behaviour:**
When pressing the clear icon button, the input text value is not cleared and it is not trigger the function which clear the state value. 

Actually keyboard appears when focus on text input and once press the icon keyboard disappears. So I guess clear icon button not able to click when keyboard appears. That why its not able to trigger the clearInput function

Please check about this issue.
